---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: fiap-sa
  namespace: fiap-sa-api
  labels:
    app: fiap-sa
stringData:
  DefaultConnection: Server=mssql-fiap-sa.mssql.svc.cluster.local,1433;Database=diners;User=sa;Password=UnRtU1FATFBAc3N3MHJk;TrustServerCertificate=True;MultipleActiveResultSets=true
