---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: fiap-sa
  namespace: fiap-sa-api
  labels:
    app: fiap-sa
stringData:
  DefaultConnection: Server=docker-fiap-diners-sqlserver,1433;Database=diners;User=sa;Password=Password1*;TrustServerCertificate=True
