---
apiVersion: v1
kind: Service
metadata:
  name: fiap-sa
  namespace: fiap-sa-api
  labels:
    app: fiap-sa
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: fiap-sa
  type: LoadBalancer
