---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiap-sa-ingress
  namespace: fiap-sa-api
spec:
  rules:
  - host: "c1ff04d40ee63d5678af8fac7cd08392.sk1.sa-east-1.eks.amazonaws.com"  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fiap-sa
            port:
              number: 8080