apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data-2
  namespace: mssql-fiap-sa
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/mssql"