apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-2
  namespace: mssql-fiap-sa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
